source 'https://supermarket.chef.io'
metadata

source chef_repo: '..'

# bumps dep to 12.14 and removes yum/apt
cookbook 'uchiwa', git: 'git://github.com/tas50/uchiwa-chef'
cookbook 'sensu', git: 'git://github.com/tas50/sensu-chef', branch: "develop"
