name             'role-base'
maintainer       'Tim Smith'
maintainer_email 'tsmith84@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role_base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'smith-packages'
depends 'smith-motd'
depends 'ntp'
depends 'sensors'
depends 'build-essential'
depends 'rsyslog'
depends 'vim'
